
apiVersion: apps/v1

kind: Deployment

metadata:

  name: bad-app

spec:

  replicas: 1

  selector:

    matchLabels:

      app: bad

  template:

    metadata:

      labels:

        app: bad

    spec:

      containers:

      - name: app

        image: nginx:1.21

        wrongField: "this will fail validation"

